name: Build and deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  build_deploy_gh_page:
    name: Build and Deploy Github Page
    runs-on: ubuntu-latest
    steps:
      - name: Check out repos develop branch
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build and Deploy Github Page
        run: |
          yarn install
          yarn build
          cp ./CNAME ./dist/

          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          yarn dlx push-dir --dir=dist --branch=gh-pages --cleanup --verbose
